# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- trunk

resources:
- repo: self

steps:
  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3
    displayName: 'Yarn Install'
    inputs:
      arguments: install

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3
    displayName: 'Yarn Build'
    inputs:
      arguments: 'run build:ssr'

  - task: Docker@0
    displayName: 'Build the image'
    inputs:
      azureSubscription: 'PodNoms Utils Connection'
      azureContainerRegistry: '{"loginServer":"podnoms.azurecr.io", "id" : "/subscriptions/58282b44-35e8-48a4-bc16-49700332985c/resourceGroups/rg-podnoms-utils/providers/Microsoft.ContainerRegistry/registries/podnoms"}'
      imageName: podnoms.azurecr.io/podnoms.pages
      qualifyImageName: false

  - task: Docker@0
    displayName: 'Push the image to ACR'
    inputs:
      azureSubscription: 'PodNoms Utils Connection'
      azureContainerRegistry: '{"loginServer":"podnoms.azurecr.io", "id" : "/subscriptions/58282b44-35e8-48a4-bc16-49700332985c/resourceGroups/rg-podnoms-utils/providers/Microsoft.ContainerRegistry/registries/podnoms"}'
      action: 'Push an image'
      imageName: podnoms.azurecr.io/podnoms.pages
      qualifyImageName: false
